services:
  ollama:
    image: ollama/ollama:0.6.0
    container_name: ollama
    restart: unless-stopped
    gpus:
      - driver: nvidia
        count: 1
    environment:
      - OLLAMA_ORIGINS=*
    ports:
      - 11434:11434
    volumes:
      - ollama-data:/root/.ollama

  litellm:
    image: ghcr.io/berriai/litellm-database:main-v1.63.6-nightly
    container_name: litellm
    restart: unless-stopped
    environment:
      - LITELLM_MASTER_KEY=### YOUR LITELLM MASTER KEY ###
      - LITELLM_SALT_KEY=### YOUR LITELLM SALT KEY ###
      - DATABASE_URL=### YOUR DATABASE URL ###
      - ANTHROPIC_API_KEY=### YOUR ANTHROPIC API KEY ###
      - AZURE_API_KEY=### YOUR AZURE API KEY HERE ###
      - AZURE_API_BASE=### AZURE API ENDPOINT URL ###
      - AZURE_API_VERSION=### AZURE API VERSION ###
      - GEMINI_API_KEY=### GEMINI API KEY HERE ###
    ports:
      - 4000:4000
    volumes:
      - $PWD/litellm-config.yaml:/app/config.yaml
    command: ["--config", "/app/config.yaml"]

  db:
    image: postgres:17
    container_name: db
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=### YOUR POSTGRES USER ###
      - POSTGRES_PASSWORD=### YOUR POSTGRES PASSWORD ###

  open-webui:
    image: ghcr.io/open-webui/open-webui:v0.6.2
    container_name: open-webui
    restart: unless-stopped
    ports:
      - 6173:8080
    volumes:
      - open-webui-data:/app/backend/data
    depends_on:
      - ollama
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY='
    extra_hosts:
      - host.docker.internal:host-gateway

volumes:
  ollama-data:
  open-webui-data:
  db-data:
